version: '3.6'
services:
  app:
    container_name: ucu-notas-api
    hostname: ucu-notas-api
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
    ports:
      - 8080:8080
